### ISSUE TITLE
Library reports 'permissions granted' when the permissions request is interrupted/cancelled

### ISSUE THREAD

**Issue by msamyatl** [cplain/consent#1]
According to `ActivityCompat#onRequestPermissionsResult`:

> It is possible that the permissions request interaction with the user is interrupted. In this case you will receive empty permissions and results arrays which should be treated as a cancellation.

Currently the library does not account for that, and so when it happens it incorrectly calls `onPermissionsGranted`

**Comment by cplain** [comment]
This has been resolved in release 1.0.2
